#  Template .NET Core build

# To run your pipeline on a Windows machine, create a self-hosted Windows runner.
# For instructions on setting up a Windows runner, see https://support.atlassian.com/bitbucket-cloud/docs/set-up-runners-for-windows/

image: mcr.microsoft.com/dotnet/sdk:8.0

pipelines:
  branches:
    development:
      - step:
          name: Build
          caches:
            - dotnetcore
          script:
            - apt-get update
            - apt-get install -y jq
            - dotnet --version
            # publish erp object
            - dotnet publish -c Release -o ./publish
            # change connection string in appsettings.json value for sms
            - tmp=$(mktemp)
            - jq '.ConnectionStrings.CatalogConnection = "$SMS_CATALOG_CONNECTION"' ./ERP.Web.API/appsettings.json > "$tmp" && mv "$tmp" ./ERP.Web.API/appsettings.json
            # publish erp sms object
            - dotnet publish -c Release -o ./publish_sms
          artifacts:
            - publish/**
            - publish_sms/**
      - step:
          name: Deployed to Tested
          deployment: Test
          runs-on:
            - self.hosted
            - windows
            - shsdev.rw
          script:
            # deploy erp object
            - C:\Windows\System32\inetsrv\appcmd.exe stop sites "ERP API"
            - Get-ChildItem -Path "D:\Hosting Spaces\TEST" -Exclude wwwroot | Remove-Item -Recurse -Force
            - Copy-Item -Path "publish\*" -Destination "D:\Hosting Spaces\TEST" -Recurse -Force
            - C:\Windows\System32\inetsrv\appcmd.exe start sites "ERP API"
            # deploy erp sms object
            - C:\Windows\System32\inetsrv\appcmd.exe stop sites "ERP API SMS"
            - Get-ChildItem -Path "D:\Hosting Spaces\TEST2" -Exclude wwwroot | Remove-Item -Recurse -Force
            - Copy-Item -Path "publish_sms\*" -Destination "D:\Hosting Spaces\TEST2" -Recurse -Force
            - C:\Windows\System32\inetsrv\appcmd.exe start sites "ERP API SMS"