#  Template .NET Core build

# To run your pipeline on a Windows machine, create a self-hosted Windows runner.
# For instructions on setting up a Windows runner, see https://support.atlassian.com/bitbucket-cloud/docs/set-up-runners-for-windows/

image: mcr.microsoft.com/dotnet/sdk:8.0

pipelines:
  branches:
    development:
      - step:
          name: Build
          caches:
            - dotnetcore
          script:
            - apt-get update
            - apt-get install -y jq
            - dotnet --version
            # publish erp object
            - dotnet publish -c Release -o ./publish
            # change connection string in appsettings.json value for sms
            - tmp=$(mktemp)
            - jq --arg conn "$SMS_CATALOG_CONNECTION" '.ConnectionStrings.CatalogConnection = $conn' ./ERP.Web.API/appsettings.json > "$tmp" && mv "$tmp" ./ERP.Web.API/appsettings.json
            # publish erp sms object
            - dotnet publish -c Release -o ./publish_sms
          artifacts:
            - publish/**
            - publish_sms/**
      - step:
          name: Deploy to Tested
          deployment: Test
          runs-on:
            - self.hosted
            - windows
            - shsdev.rw
          script:
            # deploy erp object
            - $site_path=(Get-IISSite "$Env:SITE_NAME").Applications.VirtualDirectories.PhysicalPath
            - C:\Windows\System32\inetsrv\appcmd.exe stop sites "$Env:SITE_NAME"
            - Get-ChildItem -Path "$site_path" -Exclude wwwroot | Remove-Item -Recurse -Force
            - Copy-Item -Path "publish\*" -Destination "$site_path" -Recurse -Force
            - C:\Windows\System32\inetsrv\appcmd.exe start sites "$Env:SITE_NAME"
            # deploy erp sms object
            - $site_path=(Get-IISSite "$Env:SMS_SITE_NAME").Applications.VirtualDirectories.PhysicalPath
            - C:\Windows\System32\inetsrv\appcmd.exe stop sites "$Env:SMS_SITE_NAME"
            - Get-ChildItem -Path "$site_path" -Exclude wwwroot | Remove-Item -Recurse -Force
            - Copy-Item -Path "publish_sms\*" -Destination "$site_path" -Recurse -Force
            - C:\Windows\System32\inetsrv\appcmd.exe start sites "$Env:SMS_SITE_NAME"