#  Template .NET Core build

# To run your pipeline on a Windows machine, create a self-hosted Windows runner.
# For instructions on setting up a Windows runner, see https://support.atlassian.com/bitbucket-cloud/docs/set-up-runners-for-windows/

image: mcr.microsoft.com/dotnet/sdk:8.0

pipelines:
  branches:
    development:
      - step:
          name: Build
          caches:
            - dotnetcore
          script:
            - apt-get update
            - apt-get install -y jq
            - dotnet --version
            - dotnet publish -c Release -o ./publish-$BITBUCKET_BUILD_NUMBER
            - tmp=$(mktemp)
            - jq '.ConnectionStrings.CatalogConnection = "$SMS_CATALOG_CONNECTION"' ./ERP.Web.API/appsettings.json > "$tmp" && mv "$tmp" ./ERP.Web.API/appsettings.json
            - dotnet publish -c Release -o ./publish_sms-$BITBUCKET_BUILD_NUMBER
          artifacts:
            - publish-$BITBUCKET_BUILD_NUMBER/**
            - publish_sms-$BITBUCKET_BUILD_NUMBER/**
      - step:
          name: Deployed to Tested
          deployment: Test
          runs-on:
            - self.hosted
            - windows
            - shsdev.rw
          script:
            - C:\Windows\System32\inetsrv\appcmd.exe stop sites "ERP API"
            - Get-ChildItem -Path "D:\Hosting Spaces\TEST" -Exclude wwwroot | Remove-Item -Recurse -Force
            - Copy-Item -Path "publish\*" -Destination "D:\Hosting Spaces\TEST" -Recurse -Force
            - C:\Windows\System32\inetsrv\appcmd.exe start sites "ERP API"