<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
	  <Authors>Sahassa Dev. Team</Authors>
	  <Company>Sahassa Panca Manunggal</Company>
	  <Product>Sahassa® ERP</Product>
	  <Copyright>© Sahassa. All rights reserved.</Copyright>
	  <Version>22.7.19</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Migrations\TenantMigrations\20220407034736_InitialCreate.cs.bak" />
    <None Remove="Migrations\TenantMigrations\20220407034736_InitialCreate.Designer.cs.bak" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.7" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
