// <auto-generated />
using System;
using ERP_API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ERP_API.Migrations.ERPControlMigrations
{
    [DbContext(typeof(ERPControlDbContext))]
    [Migration("20201109144904_InitialCreateShardTable")]
    partial class InitialCreateShardTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ERP_API.Entities.Control.ShardTable", b =>
                {
                    b.Property<int>("ShardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ShardID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("Shard")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ShardId");

                    b.ToTable("ShardTable");
                });
#pragma warning restore 612, 618
        }
    }
}
