// <auto-generated />
using System;
using ERP_API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ERP_API.Migrations.ERPControlMigrations
{
    [DbContext(typeof(ERPControlDbContext))]
    partial class ERPControlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ERP_API.Entities.Control.ShardTable", b =>
                {
                    b.Property<int>("ShardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ShardID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("Shard")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ShardId");

                    b.ToTable("ShardTable");
                });

            modelBuilder.Entity("ERP_API.Entities.Control.TenantDetails", b =>
                {
                    b.Property<Guid>("Shard")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TenantShard")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantSlug")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Shard");

                    b.ToTable("TenantDetails");
                });

            modelBuilder.Entity("ERP_API.Entities.Control.UserTable", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserTable");
                });
#pragma warning restore 612, 618
        }
    }
}
